-- Yetenek 2.0 — Migration 0013: lesson_instructions expansion
--
-- Her sporu 2 dersten 5 derse genişletir (3 yeni ders × 12 spor = 36 satır).
-- src/lib/lessons/curriculum.ts'deki 3-5 numaralı dersler ile birebir uyumlu.

insert into public.lesson_instructions (id, sport_slug, display_order, name, description, difficulty, instructions) values
  ('taekwondo-3', 'taekwondo', 3, 'Sol Ön Tekme (Ap Chagi)',
    'Sol diz yukarı çek, ayağı öne savur — 3 tekrarlı sol bacak tekme dizisi.', 'intermediate',
    '["Hazır duruşta başla, ağırlık sağ ayakta.","Sol dizini bel hizasına kaldır.","Ayağı düz öne uzat ve indir.","Toplam 3 tekme yap."]'::jsonb),
  ('taekwondo-4', 'taekwondo', 4, 'Yüksek Blok (Olgul Makgi)',
    'İki bilek baş üstünde — gelen darbeyi savuşturma duruşu, 2 sn sabit.', 'intermediate',
    '["Hazır duruşta başla.","İki yumruğu da başının üstüne kaldır.","Bilekler omuz hizasının üzerinde.","2 saniye sabit tut."]'::jsonb),
  ('taekwondo-5', 'taekwondo', 5, 'Yan Tekme Sıçraması',
    'Yan tekme öncesi patlayıcı dikey sıçrama — 4 tekrarlı kombinasyon.', 'advanced',
    '["Hazır duruşta başla.","Hızla çömel ve patlayıcı sıçra.","Havada bacak yan tekme pozisyonu alır.","Toplam 4 sıçrama."]'::jsonb),

  ('boks-3', 'boks', 3, 'Çapraz Yumruk (Cross)',
    'Sağ bilek öne ve hafif yukarı uzansın — 3 tekrarlı cross.', 'intermediate',
    '["Guard pozisyonunda başla.","Sağ yumruğu hızla öne uzat (arka el).","Yumruğu geri çek, guard''a dön.","Toplam 3 cross at."]'::jsonb),
  ('boks-4', 'boks', 4, 'Kapanma Çömeli (Slip)',
    'Gelen yumruktan kaçmak için hızlı alçalma — 3 tekrarlı squat.', 'intermediate',
    '["Guard pozisyonunda başla.","Hızla çömel (yumruğun altından geç).","Geri kalk, guard pozisyonuna dön.","Toplam 3 slip."]'::jsonb),
  ('boks-5', 'boks', 5, 'Uppercut',
    'Sol bilek aşağıdan yukarı patlayıcı — 4 tekrarlı çene vuruşu.', 'advanced',
    '["Guard pozisyonunda başla, dizler hafif bükülü.","Sol yumruğu bel hizasından çene hizasına patlat.","Yumruğu geri çek, guard''a dön.","Toplam 4 uppercut at."]'::jsonb),

  ('voleybol-3', 'voleybol', 3, 'Parmak Pas',
    'İki bilek baş üstünde — parmak pas hazırlık duruşu, 2 sn sabit.', 'intermediate',
    '["Hafif çömel pozisyonunda başla.","İki eli alın hizasının üstüne kaldır.","Parmak uçları yukarıyı işaret etsin.","2 saniye sabit tut."]'::jsonb),
  ('voleybol-4', 'voleybol', 4, 'Manşet Hazırlık',
    'Topu kollarla karşılamak için hızlı alçalma — 3 tekrar.', 'intermediate',
    '["Dik dur, kollar yanda.","Hızla çömel (top karşılama pozisyonu).","Kalk, başlangıca dön.","Toplam 3 tekrar."]'::jsonb),
  ('voleybol-5', 'voleybol', 5, 'Servis Sıçraması',
    'Tenis servis vuruşu için patlayıcı dikey sıçrama — 4 tekrar.', 'advanced',
    '["Dik dur, ayaklar omuz genişliğinde.","Hızla çömel.","Patlayıcı yukarı sıçra, sağ kol vuruş için yükselir.","Toplam 4 sıçrama."]'::jsonb),

  ('basketbol-3', 'basketbol', 3, 'Defansif Slide',
    'Sol ayak yana — defansif kayma için bacak uzatma, 3 tekrar.', 'intermediate',
    '["Triple threat pozisyonunda başla.","Sol ayağı yana doğru uzat (defansif kayma).","Geri çek, başlangıca dön.","Toplam 3 slide."]'::jsonb),
  ('basketbol-4', 'basketbol', 4, 'Layup Diz Çekme',
    'Sağ diz yukarı — layup atışında diz yukarı çekme fazı, 3 tekrar.', 'intermediate',
    '["Dik dur, ağırlık sol ayakta.","Sağ dizini bel hizasına yukarı çek (layup yükselişi).","İndir, başlangıca dön.","Toplam 3 layup."]'::jsonb),
  ('basketbol-5', 'basketbol', 5, 'Crossover Sıçraması',
    'Çift yönlü patlayıcı sıçrama — crossover ile dribling kombinasyonu, 4 tekrar.', 'advanced',
    '["Triple threat pozisyonunda başla.","Hızla çömel.","Patlayıcı yukarı sıçra, havada vücut yön değiştirir.","Toplam 4 sıçrama."]'::jsonb),

  ('tenis-3', 'tenis', 3, 'Backhand',
    'Sol bilek sola uzansın — çift el backhand vuruşu, 3 tekrar.', 'intermediate',
    '["Ready pozisyonunda başla.","Sol kolu sola doğru hızla uzat (backhand).","Bileği geri çek, ready pozisyonuna dön.","Toplam 3 backhand."]'::jsonb),
  ('tenis-4', 'tenis', 4, 'Volley Hazırlık',
    'İki bilek yüz hizasında — file önü volley duruşu, 2 sn.', 'intermediate',
    '["Hafif çömel pozisyonunda başla.","İki bileği yüz hizasında raket tutar gibi öne uzat.","Dirsekler hafif bükülü, gözler ileride.","2 saniye sabit tut."]'::jsonb),
  ('tenis-5', 'tenis', 5, 'Servis Atışı',
    'Sağ kol baş üstüne patlayıcı — servis vuruşu zirvesi, 4 tekrar.', 'advanced',
    '["Dik dur, ayaklar omuz genişliğinde.","Sağ kolu hızla başının üstüne kaldır (vuruş).","İndir, başlangıca dön.","Toplam 4 servis."]'::jsonb),

  ('yuzme-3', 'yuzme', 3, 'Sol Kol Kulaç',
    'Sol bilek yukarı uzansın — serbest stil sol kol kulaç simülasyonu, 3 tekrar.', 'intermediate',
    '["Dik dur, kollar yanda.","Sol bileği yukarı/ileri uzat (çekiş fazı).","Yana indir (itme fazı).","Toplam 3 kulaç."]'::jsonb),
  ('yuzme-4', 'yuzme', 4, 'Bacak Vuruşu Hazırlık',
    'Sağ ayak yukarı — kelebek/serbest stil tekme prep, 3 tekrar.', 'intermediate',
    '["Dik dur, ağırlık sol ayakta.","Sağ ayağı düz şekilde yukarı/öne uzat (tekme).","İndir, başlangıca dön.","Toplam 3 tekme."]'::jsonb),
  ('yuzme-5', 'yuzme', 5, 'Dolfin Dalga',
    'Tüm vücut dalga hareketi — kelebek stil patlayıcı çömel, 4 tekrar.', 'advanced',
    '["Dik dur, kollar başının üstünde birleşik.","Hızla çömel (dalga inişi).","Patlayıcı kalk.","Toplam 4 dalga."]'::jsonb),

  ('futbol-3', 'futbol', 3, 'Sol Ayak Pas',
    'Sol ayağın iç yanı ile yana pas — zayıf ayak gelişimi, 3 tekrar.', 'intermediate',
    '["Hazır duruşta başla, ağırlık sağ ayakta.","Sol ayağın iç yanını sola doğru uzat (pas vermek gibi).","Ayağı geri çek, başlangıca dön.","Toplam 3 pas."]'::jsonb),
  ('futbol-4', 'futbol', 4, 'Kaleci Duruşu',
    'İki yumruk yüz hizasında — kaleci hazır pozisyonu, 2 sn sabit.', 'intermediate',
    '["Hafif çömel, ayaklar omuz genişliğinde.","İki bileği yüz hizasına kaldır, dirsekler bükülü.","Vücut hafif öne eğik, gözler ileride.","2 saniye sabit tut."]'::jsonb),
  ('futbol-5', 'futbol', 5, 'Volley Sıçraması',
    'Havadan gelen topa vuruş — patlayıcı dikey sıçrama, 4 tekrar.', 'advanced',
    '["Hazır duruşta başla.","Hızla çömel.","Patlayıcı yukarı sıçra (havada volley vuruşu).","Toplam 4 sıçrama."]'::jsonb),

  ('atletizm-3', 'atletizm', 3, 'Sol Diz Çekme',
    'Sprint sol diz çekme drili — sol dizi bel hizasına 3 kez çek.', 'intermediate',
    '["Dik dur.","Sol dizini bel hizasına yukarı çek.","İndir, başlangıca dön.","Toplam 3 sol diz çekme."]'::jsonb),
  ('atletizm-4', 'atletizm', 4, 'Maraton Duruş',
    'Uzun mesafe koşu hazır duruşu — dengeli, gevşek, 2 sn sabit.', 'intermediate',
    '["Ayaklar omuz genişliğinde, paralel.","Dizler hafif bükülü, omuzlar gevşek.","Kollar yanda doğal asılı.","2 saniye sabit tut."]'::jsonb),
  ('atletizm-5', 'atletizm', 5, 'Yüksek Sıçrama',
    'Patlayıcı dikey sıçrama — yüksek atlama / üçadım simülasyonu, 4 tekrar.', 'advanced',
    '["Dik dur, ayaklar omuz genişliğinde.","Hızla çömel.","Patlayıcı yukarı sıçra, dizleri havada çek.","Toplam 4 sıçrama."]'::jsonb),

  ('cimnastik-3', 'cimnastik', 3, 'Y Duruş',
    'İki kol baş üstünde V şeklinde — denge ve esneklik duruşu, 3 sn sabit.', 'intermediate',
    '["Dik dur, ayaklar bitişik.","İki kolu da yukarı V şeklinde aç.","Bilekler omuz hizasının üzerinde.","3 saniye sabit tut."]'::jsonb),
  ('cimnastik-4', 'cimnastik', 4, 'Köprü Hazırlık',
    'Sol bilek yukarı uzansın — köprü hareketi için kol açma, 3 tekrar.', 'intermediate',
    '["Dik dur, kollar yanda.","Sol bileği başının üstüne yukarı uzat.","İndir, başlangıca dön.","Toplam 3 tekrar."]'::jsonb),
  ('cimnastik-5', 'cimnastik', 5, 'Pike Jump',
    'Patlayıcı sıçrama, havada bacaklar düz öne — 4 tekrarlı pike.', 'advanced',
    '["Dik dur, ayaklar omuz genişliğinde.","Hızla çömel.","Patlayıcı sıçra, havada bacaklar düz öne uzansın (pike).","Toplam 4 pike jump."]'::jsonb),

  ('judo-3', 'judo', 3, 'Tai Sabaki (Yan Adım)',
    'Sağ ayak yana uzansın — rakibin etrafında dönme adımı, 3 tekrar.', 'intermediate',
    '["Hazır duruşta başla.","Sağ ayağı yana doğru uzat (yan adım).","Geri çek, başlangıca dön.","Toplam 3 yan adım."]'::jsonb),
  ('judo-4', 'judo', 4, 'Kuzushi (Denge Bozma)',
    'İki bilek yüz hizasında — rakibi tutma ve dengesini bozma, 2 sn.', 'intermediate',
    '["Hafif çömel pozisyonunda başla.","İki bileği yüz hizasına kaldır (gi tutma simülasyonu).","Dirsekler bükülü, gözler ileride.","2 saniye sabit tut."]'::jsonb),
  ('judo-5', 'judo', 5, 'Uchi Komi Sıçrama',
    'Atış öncesi patlayıcı yukarı kaldırma — 4 tekrarlı sıçrama.', 'advanced',
    '["Hazır duruşta başla, dizler hafif bükülü.","Hızla çömel.","Patlayıcı yukarı sıçra (rakibi havalandırma simülasyonu).","Toplam 4 sıçrama."]'::jsonb),

  ('masa-tenisi-3', 'masa-tenisi', 3, 'Backhand Vuruş',
    'Sol kol sola, hızlı backhand simülasyonu — 3 tekrar.', 'intermediate',
    '["Hazır duruşta başla.","Sol kolu sola hızla uzat (backhand).","Geri çek.","Toplam 3 vuruş."]'::jsonb),
  ('masa-tenisi-4', 'masa-tenisi', 4, 'Servis Hazırlık',
    'Hafif çömel ve raket aşağıda — masa tenisi servis duruşu, 2 sn.', 'intermediate',
    '["Ayaklar omuz genişliğinde.","Dizler bükülü, vücut hafif öne eğik.","Sağ kol bel hizasında raket tutar gibi.","2 saniye sabit tut."]'::jsonb),
  ('masa-tenisi-5', 'masa-tenisi', 5, 'Smash',
    'Sağ kol baş üstüne patlayıcı — yüksek topa smash vuruşu, 4 tekrar.', 'advanced',
    '["Hazır duruşta başla.","Sağ kolu hızla başının üstüne kaldır (smash).","İndir, başlangıca dön.","Toplam 4 smash."]'::jsonb),

  ('badminton-3', 'badminton', 3, 'Clear Vuruşu',
    'Sol bilek baş üstüne — backhand clear ile arka kort vuruşu, 3 tekrar.', 'intermediate',
    '["Hazır duruşta başla.","Sol kolu başının üstüne hızla kaldır (clear).","İndir, başlangıca dön.","Toplam 3 clear."]'::jsonb),
  ('badminton-4', 'badminton', 4, 'Drop Shot',
    'Sağ bilek sağa yumuşak uzansın — file önü drop vuruşu, 3 tekrar.', 'intermediate',
    '["Hazır duruşta başla.","Sağ kolu sağa doğru hafif uzat (drop shot).","Geri çek.","Toplam 3 drop."]'::jsonb),
  ('badminton-5', 'badminton', 5, 'Lunge Hamlesi',
    'Patlayıcı çömel — file önüne lunge ile uzanma, 4 tekrarlı squat.', 'advanced',
    '["Hazır duruşta başla.","Hızla çömel (öne uzanan lunge).","Geri kalk, başlangıca dön.","Toplam 4 lunge."]'::jsonb)
on conflict (id) do update set
  sport_slug = excluded.sport_slug,
  display_order = excluded.display_order,
  name = excluded.name,
  description = excluded.description,
  difficulty = excluded.difficulty,
  instructions = excluded.instructions,
  updated_at = now();
